// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/expense": {
            "post": {
                "description": "Creates a new Expense for an Expense List",
                "tags": [
                    "Expenses"
                ],
                "summary": "Create Expense",
                "parameters": [
                    {
                        "description": "Expense Data",
                        "name": "expense",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Expense"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated Expense List with new Expense, Compensation and Shares",
                        "schema": {
                            "$ref": "#/definitions/models.ExpenseListWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/expense-list": {
            "post": {
                "description": "Creates a new Expense list with given data for a specified user",
                "tags": [
                    "Expenses"
                ],
                "summary": "Create Expense List",
                "parameters": [
                    {
                        "description": "Expense List Data",
                        "name": "expenseList",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.ExpenseListWrapper"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Created Expense List",
                        "schema": {
                            "$ref": "#/definitions/models.ExpenseListWrapper"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/expense-list/join": {
            "post": {
                "description": "Join ExpenseList with valid inviteCode",
                "tags": [
                    "Expenses"
                ],
                "summary": "Join Expense List",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Expense List Id",
                        "name": "expenseListId",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Invite Code",
                        "name": "inviteCode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        },
        "/expense-lists": {
            "get": {
                "description": "Retrieves the list of expenses for a specified user.",
                "tags": [
                    "Expenses"
                ],
                "summary": "Get Expense Lists",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Bearer Token",
                        "name": "Authorization",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "List of user expense lists",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ExpenseListWrapper"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Expense": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "buyer": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "expenseListId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.ExpenseList": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "creatorId": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "emoji": {
                    "type": "string"
                },
                "expenses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Expense"
                    }
                },
                "id": {
                    "type": "string"
                },
                "inviteCode": {
                    "type": "string"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Participant"
                    }
                },
                "title": {
                    "type": "string"
                },
                "totalCost": {
                    "type": "number"
                }
            }
        },
        "models.ExpenseListCompensation": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "models.ExpenseListShare": {
            "type": "object",
            "properties": {
                "difference": {
                    "type": "number"
                },
                "expenseAmount": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "numberOfExpenses": {
                    "type": "integer"
                },
                "share": {
                    "type": "number"
                }
            }
        },
        "models.ExpenseListWrapper": {
            "type": "object",
            "properties": {
                "compensations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ExpenseListCompensation"
                    }
                },
                "expenseList": {
                    "$ref": "#/definitions/models.ExpenseList"
                },
                "shares": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ExpenseListShare"
                    }
                }
            }
        },
        "models.Participant": {
            "type": "object",
            "properties": {
                "avatarUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Equaly Backend",
	Description:      "This is the backend for the equaly cost management app",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
