basePath: /v1
definitions:
  models.Expense:
    properties:
      amount:
        type: number
      buyer:
        type: string
      date:
        type: string
      description:
        type: string
      expenseListId:
        type: string
      id:
        type: string
      participants:
        type: string
    type: object
  models.ExpenseList:
    properties:
      color:
        type: string
      creatorId:
        type: string
      currency:
        type: string
      emoji:
        type: string
      expenses:
        items:
          $ref: '#/definitions/models.Expense'
        type: array
      id:
        type: string
      participants:
        items:
          $ref: '#/definitions/models.Participant'
        type: array
      title:
        type: string
      totalCost:
        type: number
    type: object
  models.Participant:
    properties:
      avatarUrl:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is the backend for the equaly cost management app
  title: Equaly Backend
  version: "1.0"
paths:
  /expense:
    post:
      description: Creates a new Expense for an Expense List
      parameters:
      - description: Expense Data
        in: body
        name: expense
        required: true
        schema:
          $ref: '#/definitions/models.Expense'
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create Expense
      tags:
      - Expenses
  /expense-list:
    post:
      description: Creates a new Expense list with given data for a specified user
      parameters:
      - description: Expense List Data
        in: body
        name: expenseList
        required: true
        schema:
          $ref: '#/definitions/models.ExpenseList'
      responses:
        "200":
          description: Success
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Create Expense List
      tags:
      - Expenses
  /expense-lists:
    get:
      description: Retrieves the list of expenses for a specified user.
      parameters:
      - description: User ID to retrieve expenses for
        in: query
        name: userId
        required: true
        type: string
      responses:
        "200":
          description: List of user expenses
          schema:
            items:
              $ref: '#/definitions/models.Expense'
            type: array
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
      summary: Get Expense Lists
      tags:
      - Expenses
swagger: "2.0"
